// console.log('min')

// const show = document.querySelector('.content')
// const eleDiv= document.createElement('div')
// show.append(eleDiv)
// const pName= document.createElement ('p')
// const img = document. createElement ('img')
// img.setAttribute('src',"https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__340.jpg")
// const pSummary= document.createElement('p')
// eleDiv.append(pName,img,pSummary)
// eleDiv.classList.add('gohome')
// eleDiv.classList.add('des')
// eleDiv.classList.add('lg-col-12')